# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: lets_go_chat
    ports:
      - "5432:5432"
    volumes:
      - /home/alica/lets-go-chat-pgsql:/var/lib/postgresql/data

  adminer:
    container_name: adminer-pgs
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - "9008:8080"


